name: Post-Merge Processing

on:
  push:
    branches:
      - main

jobs:
  process_merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git user
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install boto3

      - name: Check if Latest Commit is a Merge Commit
        id: check_merge
        run: |
          PARENT_COUNT=$(git rev-list --count --parents -n 1 HEAD | awk '{print NF-1}')
          echo "Parent count: $PARENT_COUNT"
          if [ "$PARENT_COUNT" -gt 1 ]; then
            echo "is_merge=true" >> $GITHUB_OUTPUT
          else
            echo "is_merge=false" >> $GITHUB_OUTPUT
          fi

      - name: Get Associated Pull Request
        if: steps.check_merge.outputs.is_merge == 'true'
        id: get_pr
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const commit_sha = '${{ github.sha }}';
            const prs = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: commit_sha,
            });
            if (prs.data.length > 0) {
              const pr = prs.data[0];
              core.setOutput('pr_number', pr.number.toString());
              core.setOutput('pr_body', pr.body || '');
            } else {
              core.setFailed('No pull request found for this commit.');
            }

      - name: Parse Pull Request Description
        if: steps.get_pr.outputs.pr_number
        uses: actions/github-script@v6
        id: parse_pr
        with:
          script: |
            const prBody = steps.get_pr.outputs.pr_body;
            const filenameMatch = prBody.match(/^Filename:\s*(.+)$/m);
            if (!filenameMatch) throw new Error('Filename not found or invalid in PR description.');
            core.setOutput('filename', filenameMatch[1].trim());

      - name: Upload the ROM and new JSON and CSV files to S3
        if: steps.get_pr.outputs.pr_number
        run: |
            ./upload_rom  "${{ steps.parse_pr.outputs.filename }}" --path=./
        env:
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      
      - name: Delete the ROM and remove it from the repository
        if: steps.get_pr.outputs.pr_number
        run: |
            rm roms.csv
            rm "${{ steps.parse_pr.outputs.filename }}"
            git rm "${{ steps.parse_pr.outputs.filename }}"
            git add roms.json
            git commit -m "Add ${{steps.parse_pr.outputs.rom_name}}"
            git push
  
      - name: Notify Maintainers
        if: failure()
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: ${{ steps.get_pr.outputs.pr_number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'An error occurred while processing your ROM submission. Please check the repository logs for more details.'
            })
