name: Process Pull Request

on:
  pull_request:
    types: [opened, edited, reopened]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install boto3

      - name: Parse Pull Request Description
        uses: actions/github-script@v6
        id: parse_pr
        with:
          script: |
            const prBody = context.payload.pull_request.body;
      
            const filenameMatch = prBody.match(/^Filename:\s*(.+)$/m);
            const nameMatch = prBody.match(/^Name:\s*(.+)$/m);
            const descriptionMatch = prBody.match(/^Description:\s*(.+)$/m);
            const tagsMatch = prBody.match(/^Tags:\s*(.+)$/m);
            const sizeMatch = prBody.match(/^Size:\s*(\d+)$/m);
      
            if (!filenameMatch) throw new Error('Filename not found or invalid in PR description.');
            if (!nameMatch) throw new Error('Name not found or invalid in PR description.');
            if (!descriptionMatch) throw new Error('Description not found or invalid in PR description.');
            if (!tagsMatch) throw new Error('Tags not found or invalid in PR description.');
            if (!sizeMatch || ![32, 64, 128].includes(parseInt(sizeMatch[1]))) {
              throw new Error('Size must be 32, 64, or 128.');
            }
      
            core.setOutput('filename', filenameMatch[1].trim());
            core.setOutput('rom_name', nameMatch[1].trim());
            core.setOutput('description', descriptionMatch[1].trim());
            core.setOutput('tags', tagsMatch[1].trim());
            core.setOutput('size_kb', sizeMatch[1].trim());
        
      - name: Display Parsed Data
        run: |
          echo "Filename: ${{ steps.parse_pr.outputs.filename }}"
          echo "Name: ${{ steps.parse_pr.outputs.rom_name }}"
          echo "Description: ${{ steps.parse_pr.outputs.description }}"
          echo "Tags: ${{ steps.parse_pr.outputs.tags }}"
          echo "Size (KB): ${{ steps.parse_pr.outputs.size_kb }}"
